export const EXTERNAL_LINKS = {
	GITHUB: "https://github.com/VibexInc/Vibex",
	GITHUB_DISCUSSIONS: "https://github.com/VibexInc/Vibex/discussions",
	DISCORD: "https://discord.gg/vibex",
	REDDIT: "https://reddit.com/r/Vibex",
	X: "https://x.com/vibex",
	LINKEDIN: "https://www.linkedin.com/company/vibex",
	TIKTOK: "https://www.tiktok.com/@vibex",
	BLUESKY: "https://bsky.app/profile/vibex.bsky.social",
	YOUTUBE: "https://www.youtube.com/@VibexYT",
	DOCUMENTATION: "https://docs.vibex.com",
	CAREERS: "https://careers.vibex.com",
	ISSUES: "https://github.com/VibexInc/Vibex/issues",
	FEATURE_REQUESTS: "https://github.com/VibexInc/Vibex/discussions/categories/feature-requests",
	COMMUNITY: "https://github.com/VibexInc/Vibex/discussions",
	CHANGELOG: "https://github.com/VibexInc/Vibex/blob/main/CHANGELOG.md",
	PRIVACY_POLICY_EXTENSION: "https://github.com/VibexInc/Vibex/blob/main/PRIVACY.md",
	INTEGRATIONS: "https://docs.vibex.com/community",
	TUTORIALS: "https://docs.vibex.com/tutorial-videos",
	MARKETPLACE: "https://marketplace.visualstudio.com/items?itemName=RooVeterinaryInc.vibex-code-code",
	SECURITY: "https://trust.vibex.com",
	EVALS: "https://vibex.com/evals",
	BLOG: "https://blog.vibex.com",
	OFFICE_HOURS_PODCAST: "https://www.youtube.com/@VibexYT/podcasts",
	FAQ: "https://vibex.com/#faq",
	TESTIMONIALS: "https://vibex.com/#testimonials",
	CLOUD_APP_LOGIN: "https://app.vibex.com/sign-in",
	CLOUD_APP_SIGNUP: "https://app.vibex.com/sign-up",
	CLOUD_APP_SIGNUP_HOME: "https://app.vibex.com/sign-up?redirect_url=/cloud-agents/setup",
	CLOUD_APP_SIGNUP_PRO: "https://app.vibex.com/sign-up?redirect_url=/cloud-agents/setup",
	SUPPORT: "mailto:support@vibex.com",
}

export const INTERNAL_LINKS = {
	PRIVACY_POLICY_WEBSITE: "/privacy",
}
